/*
 * go_flutter_ex Product
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/bluemon0919/webapi/go"
)

func main() {
	log.Printf("Server started")

	ProductApiService := openapi.NewProductApiService()
	ProductApiController := openapi.NewProductApiController(ProductApiService)

	router := openapi.NewRouter(ProductApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
