/*
 * go_flutter_ex Product
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// ProductApiRouter defines the required methods for binding the api requests to a responses for the ProductApi
// The ProductApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ProductApiServicer to perform the required actions, then write the service results to the http response.
type ProductApiRouter interface { 
	GetProduct(http.ResponseWriter, *http.Request)
}


// ProductApiServicer defines the api actions for the ProductApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type ProductApiServicer interface { 
	GetProduct(string) (interface{}, error)
}
