/*
 * go_flutter_ex Product
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
)

var table [3]Product = [3]Product{
	{"0", "Apple", 100},
	{"1", "Orange", 200},
	{"2", "Peach", 200},
}

// ProductApiController binds http requests to an api service and writes the service results to the http response
type ProductApiController struct {
	service ProductApiServicer
}

// NewProductApiController creates a default api controller
func NewProductApiController(s ProductApiServicer) Router {
	return &ProductApiController{service: s}
}

// Routes returns all of the api route for the ProductApiController
func (c *ProductApiController) Routes() Routes {
	return Routes{
		{
			"GetProduct",
			strings.ToUpper("Get"),
			"/api/product",
			c.GetProduct,
		},
	}
}

// GetProduct - get product information
func (c *ProductApiController) GetProduct(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)

	sID := r.URL.Query()["productId"][0]
	id, err := strconv.Atoi(sID)
	if err != nil {
		//w.WriteHeader(http.StatusBadRequest)
		return
	}

	product := Product{
		Id:    table[id].Id,
		Name:  table[id].Name,
		Price: table[id].Price,
	}
	json.NewEncoder(w).Encode(product)

	fmt.Println("go test OK")
}
