/*
 * go_flutter_ex Product
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// ProductApiService is a service that implents the logic for the ProductApiServicer
// This service should implement the business logic for every endpoint for the ProductApi API. 
// Include any external packages or services that will be required by this service.
type ProductApiService struct {
}

// NewProductApiService creates a default api service
func NewProductApiService() ProductApiServicer {
	return &ProductApiService{}
}

// GetProduct - get product information
func (s *ProductApiService) GetProduct(productId string) (interface{}, error) {
	// TODO - update GetProduct with the required logic for this service method.
	// Add api_product_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetProduct' not implemented")
}
