/*
 * go_flutter_ex Product
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Product struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Price int64 `json:"price"`
}
