openapi: 3.0.0
info:
  license:
    name: MIT
  title: go_flutter_ex Product
  version: 0.1.0
servers:
- url: http://localhost:8080/api/
paths:
  /product:
    get:
      operationId: getProduct
      parameters:
      - description: query target product id
        explode: true
        in: query
        name: productId
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: return product information
      summary: get product information
      tags:
      - product
components:
  schemas:
    Product:
      example:
        price: 0
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        price:
          format: int64
          type: integer
      required:
      - id
      - name
      - price
